package klasy;
// Generated 2013-05-31 18:05:26 by Hibernate Tools 3.2.1.GA



/**
 * Film generated by hbm2java
 */
public class Film  implements java.io.Serializable {


     private int id;
     private String nazwa;
     private int kategoriaWiekowa;
     private int czasTrwania;
     private String opis;

    public Film() {
    }

	
    public Film(String nazwa, int kategoriaWiekowa, int czasTrwania) {
        this.id = id;
        this.nazwa = nazwa;
        this.kategoriaWiekowa = kategoriaWiekowa;
        this.czasTrwania = czasTrwania;
    }
    public Film(String nazwa, int kategoriaWiekowa, int czasTrwania, String opis) {
       this.id = id;
       this.nazwa = nazwa;
       this.kategoriaWiekowa = kategoriaWiekowa;
       this.czasTrwania = czasTrwania;
       this.opis = opis;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNazwa() {
        return this.nazwa;
    }
    
    public void setNazwa(String nazwa) {
        this.nazwa = nazwa;
    }
    public int getKategoriaWiekowa() {
        return this.kategoriaWiekowa;
    }
    
    public void setKategoriaWiekowa(int kategoriaWiekowa) {
        this.kategoriaWiekowa = kategoriaWiekowa;
    }
    public int getCzasTrwania() {
        return this.czasTrwania;
    }
    
    public void setCzasTrwania(int czasTrwania) {
        this.czasTrwania = czasTrwania;
    }
    public String getOpis() {
        return this.opis;
    }
    
    public void setOpis(String opis) {
        this.opis = opis;
    }




}


