package klasy;
// Generated 2013-05-31 18:05:26 by Hibernate Tools 3.2.1.GA



/**
 * Rezerwacja generated by hbm2java
 */
public class Rezerwacja  implements java.io.Serializable {


     private Integer id;
     private int idSeansu;
     private int rzad;
     private int nrSiedzenia;
     private String nazwisko;
     private Boolean zatwierdzona;

    public Rezerwacja() {
    }

	
    public Rezerwacja(int idSeansu, int rzad, int nrSiedzenia, String nazwisko) {
        this.idSeansu = idSeansu;
        this.rzad = rzad;
        this.nrSiedzenia = nrSiedzenia;
        this.nazwisko = nazwisko;
    }
    public Rezerwacja(int idSeansu, int rzad, int nrSiedzenia, String nazwisko, Boolean zatwierdzona) {
       this.idSeansu = idSeansu;
       this.rzad = rzad;
       this.nrSiedzenia = nrSiedzenia;
       this.nazwisko = nazwisko;
       this.zatwierdzona = zatwierdzona;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getIdSeansu() {
        return this.idSeansu;
    }
    
    public void setIdSeansu(int idSeansu) {
        this.idSeansu = idSeansu;
    }
    public int getRzad() {
        return this.rzad;
    }
    
    public void setRzad(int rzad) {
        this.rzad = rzad;
    }
    public int getNrSiedzenia() {
        return this.nrSiedzenia;
    }
    
    public void setNrSiedzenia(int nrSiedzenia) {
        this.nrSiedzenia = nrSiedzenia;
    }
    public String getNazwisko() {
        return this.nazwisko;
    }
    
    public void setNazwisko(String nazwisko) {
        this.nazwisko = nazwisko;
    }
    public Boolean getZatwierdzona() {
        return this.zatwierdzona;
    }
    
    public void setZatwierdzona(Boolean zatwierdzona) {
        this.zatwierdzona = zatwierdzona;
    }




}


