package klasy;
// Generated Jun 22, 2013 10:14:45 PM by Hibernate Tools 3.2.1.GA



/**
 * Rezerwacja generated by hbm2java
 */
public class Rezerwacja  implements java.io.Serializable {


     private Integer id;
     private Seans seans;
     private int rzad;
     private int nrSiedzenia;
     private String nazwisko;
     private Boolean zatwierdzona;

    public Rezerwacja() {
    }

	
    public Rezerwacja(Seans seans, int rzad, int nrSiedzenia, String nazwisko) {
        this.seans = seans;
        this.rzad = rzad;
        this.nrSiedzenia = nrSiedzenia;
        this.nazwisko = nazwisko;
    }
    public Rezerwacja(Seans seans, int rzad, int nrSiedzenia, String nazwisko, Boolean zatwierdzona) {
       this.seans = seans;
       this.rzad = rzad;
       this.nrSiedzenia = nrSiedzenia;
       this.nazwisko = nazwisko;
       this.zatwierdzona = zatwierdzona;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Seans getSeans() {
        return this.seans;
    }
    
    public void setSeans(Seans seans) {
        this.seans = seans;
    }
    public int getRzad() {
        return this.rzad;
    }
    
    public void setRzad(int rzad) {
        this.rzad = rzad;
    }
    public int getNrSiedzenia() {
        return this.nrSiedzenia;
    }
    
    public void setNrSiedzenia(int nrSiedzenia) {
        this.nrSiedzenia = nrSiedzenia;
    }
    public String getNazwisko() {
        return this.nazwisko;
    }
    
    public void setNazwisko(String nazwisko) {
        this.nazwisko = nazwisko;
    }
    public Boolean getZatwierdzona() {
        return this.zatwierdzona;
    }
    
    public void setZatwierdzona(Boolean zatwierdzona) {
        this.zatwierdzona = zatwierdzona;
    }




}


