package klasy;
// Generated Jun 22, 2013 10:14:45 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Sala generated by hbm2java
 */
public class Sala  implements java.io.Serializable {


     private Integer id;
     private int szerokosc;
     private int wysokosc;
     private int numer;
     private Set seanses = new HashSet(0);

    public Sala() {
    }

	
    public Sala(int szerokosc, int wysokosc, int numer) {
        this.szerokosc = szerokosc;
        this.wysokosc = wysokosc;
        this.numer = numer;
    }
    public Sala(int szerokosc, int wysokosc, int numer, Set seanses) {
       this.szerokosc = szerokosc;
       this.wysokosc = wysokosc;
       this.numer = numer;
       this.seanses = seanses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getSzerokosc() {
        return this.szerokosc;
    }
    
    public void setSzerokosc(int szerokosc) {
        this.szerokosc = szerokosc;
    }
    public int getWysokosc() {
        return this.wysokosc;
    }
    
    public void setWysokosc(int wysokosc) {
        this.wysokosc = wysokosc;
    }
    public int getNumer() {
        return this.numer;
    }
    
    public void setNumer(int numer) {
        this.numer = numer;
    }
    public Set getSeanses() {
        return this.seanses;
    }
    
    public void setSeanses(Set seanses) {
        this.seanses = seanses;
    }




}


