package klasy;
// Generated 2013-05-31 18:05:26 by Hibernate Tools 3.2.1.GA

import java.util.Set;




/**
 * Sala generated by hbm2java
 */
public class Sala  implements java.io.Serializable {


     private Integer id;
     private int szerokosc;
     private int wysokosc;
     private int numer;
    public Sala() {
    }

    public Sala(int szerokosc, int wysokosc, int numer) {
       this.szerokosc = szerokosc;
       this.wysokosc = wysokosc;
       this.numer = numer;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getSzerokosc() {
        return this.szerokosc;
    }
    
    public void setSzerokosc(int szerokosc) {
        this.szerokosc = szerokosc;
    }
    public int getWysokosc() {
        return this.wysokosc;
    }
    
    public void setWysokosc(int wysokosc) {
        this.wysokosc = wysokosc;
    }
    public int getNumer() {
        return this.numer;
    }
    
    public void setNumer(int numer) {
        this.numer = numer;
    }




}


