package klasy;
// Generated Jun 22, 2013 10:14:45 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Seans generated by hbm2java
 */
public class Seans  implements java.io.Serializable {


     private Integer id;
     private Film film;
     private Sala sala;
     private Date data;
     private int idFilmu;
     private int idSali;
     private Set rezerwacjas = new HashSet(0);

    public Seans() {
    }

	
    public Seans(Film film, Sala sala, Date data) {
        this.film = film;
        this.sala = sala;
        this.data = data;
    }
    
    public Seans(int idFilmu, int idSali, Date data) {
        this.idFilmu = idFilmu;
        this.idSali = idSali;
        this.data = data;
    }
    
    public Seans(Film film, Sala sala, Date data, Set rezerwacjas) {
       this.film = film;
       this.sala = sala;
       this.data = data;
       this.rezerwacjas = rezerwacjas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Film getFilm() {
        return this.film;
    }
    
    public void setFilm(Film film) {
        this.film = film;
    }
    public Sala getSala() {
        return this.sala;
    }
    
    public void setSala(Sala sala) {
        this.sala = sala;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public Set getRezerwacjas() {
        return this.rezerwacjas;
    }
    
    public void setRezerwacjas(Set rezerwacjas) {
        this.rezerwacjas = rezerwacjas;
    }

    public int getIdFilmu() {
        return this.idFilmu;
    }
    
    public void setIdFilmu(int id) {
        this.idFilmu = id;
    }

    public int getIdSali() {
        return this.idSali;
    }
    
    public void setIdSali(int id) {
        this.idSali = id;
    }

}


