package klasy;
// Generated 2013-05-31 18:05:26 by Hibernate Tools 3.2.1.GA


import java.text.SimpleDateFormat;
import java.util.Date;
import javax.persistence.Column;
import org.hibernate.annotations.Type;

/**
 * Seans generated by hbm2java
 */
public class Seans  implements java.io.Serializable {


     private Integer id;
     private int idFilmu;
     private int idSali;
     @Column
     @Type(type="date")
     private Date data;
     private Film film;
     private Sala sala;
     
    public Seans() {
    }

    public Seans(int idFilmu, int idSali, Date data) {
       this.idFilmu = idFilmu;
       this.idSali = idSali;
       this.data = data;
    }
    
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    public Film getFilm() {
        return this.film;
    }
    
    public void setFilm(Film film) {
        this.film = film;
    }

    public int getIdFilmu() {
    return this.idFilmu;
    }
    public void setIdFilmu(int idFilmu) {
    this.idFilmu = idFilmu;
    }
    public int getIdSali() {
    return this.idSali;
    }
    public void setIdSali(int idSali) {
    this.idSali = idSali;
    }
    
    public Date getData() {
        return this.data;
    }
    
    public String getDataString() {
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd.MM.yyyy kk:mm");
        return dateFormat.format(this.data);
    }
    
    public void setData(Date data) {
        this.data = data;
    }

    public Sala getSala() {
        return sala;
    }

    public void setSala(Sala sala) {
        this.sala = sala;
    }

}


